### ISSUE TITLE
Make subscribing to AWS event services configurable

### ISSUE THREAD

**Issue by bronaghs** [ManageIQ/manageiq-providers-amazon#126]
Define a blacklist of AWS services we do not wish to capture events from.
Pivotal story:https://www.pivotaltracker.com/story/show/138951121

 A new setting would be added to config/settings.yml, some like this:
    ```:ems_amazon:```
   ``` :disabled_event_services: ["AWS_Config", "CloudTrail", "EC2", "ELB", "ESB" ]```

Events from a service included in ```:disabled_event_services ``` will not be collected on AWS.

ManageIQ currently receives events from the following three AWS services: 

- AWS_Config,
- CloudTrail,
- CloudWatch.

The process for enabling or disabling event collection from each is not the same; AWS_Config and CloudWatch have an ON/OFF switch that can be flipped. CloudWatch is more complicated; it contains a set of rules where a rule applies to a single service eg EC2, ELB, EBS. A rule will be disabled if the service it applies to has been marked as disabled in ```disabled_event_services```. For example:

```:ems_amazon:```
``` :disabled_event_services: ["EC2", "ELB" ]```

 CloudWatch event rules that apply to the EC2 and ELB services will be disabled on AWS preventing events for ELB and EC2 from being emitted, all other CloudWatch event rules will remain enabled.

####    Consideration(s):

- Maybe not directly relevant to this GitHub issue, but during CloudTrail setup, a trail can be applied to all regions, see screenshot below. In ManageIQ, an EMS is tied to a specific region which means each EMS will receive the same CloudTrail events. An excerpt from the [AWS documentation](http://docs.aws.amazon.com/awscloudtrail/latest/userguide/configure-cloudtrail-to-send-notifications.html):

_"When you configure notifications for a trail that applies to all regions, notifications from all regions are sent to the Amazon SNS topic that you specify. If you have one or more region-specific trails, you must create a separate topic for each region and subscribe to each individually."_

![screen shot 2017-02-03 at 1 13 12 pm 2](https://cloud.githubusercontent.com/assets/4379675/22602777/9ff3f082-ea12-11e6-95bd-5f5046b0d474.png)

**Comment by bronaghs** [comment]
@blomquisg -  I bet you are thinking that we can rename the topic to something more generic like MIQ_AWS_Events are something. That will break the existing AWS_Config configuration and will require some logic be implemented to fix it. We should mull over it given that AWS_Config might be deprecated leaving behind an irrelevant topic name.

**Comment by durandom** [comment]
@bronaghs great that you look into this - somewhat related https://github.com/ManageIQ/manageiq/issues/7785#issuecomment-209468455

**Comment by durandom** [comment]
@dayleparker can you track this and create doc as needed? Thanks

**Comment by Ladas** [comment]
@bronaghs right so we would need something like "MIQ_events_topic_<region_name>". This is very important, good catch @bronaghs. :-) @durandom I wonder, how was this solved for AWSConfig? Did we get all events from all regions in that one topic?

Another thing to investigate might be IAM accounts, if we say we will create a provider per IAM, how does that align with Topic names and Events. @blomquisg could we get another AWS account so @bronaghs can try this? Although IAM users seems to be settable under one account too, not sure how to approach those.

**Comment by bascar** [comment]
@bronaghs looks good. You may already know but to point out:The region name format should be normalized and per the docs on naming, Topic names are limited to 256 characters. Alphanumeric characters plus hyphens (-) and underscores (_) are allowed... and of course the official Region names have spaces, parenthesis and illegal chars :/ however, they need them for ARN composition.

**Comment by bronaghs** [comment]
@Ladas 
To answer your question:
> I wonder, how was this solved for AWSConfig? Did we get all events from all regions in that one topic?

Multiple regions can have an event topic with the same name and they would still be considered unique because the topic ARN contains the region making it unique, eg:
- For the US West N. California region the ARN would be:
 arn:aws:sns:**us-west-1**:200278856672:AWSConfig_topic
- For the US West Oregon region the ARN would be:
arn:aws:sns:**us-west-2**:200278856672:AWSConfig_topic

In ManageIQ, when an event catcher starts up it will look for (or create) the topic "AWSConfig" that exists in the region of the EMS, this guarantees we will only subscribe to events for the correct region.

**Comment by Ladas** [comment]
@bronaghs awesome. That means the regions are solved also for CloudWatch, right? So last confusing thing might be the IAM accounts I think. :-)

**Comment by bronaghs** [comment]
@Ladas - 
> That means the regions are solved also for CloudWatch, right?

Yes. 


Referring to the screenshot I inserted above; I have been investigating what happens when a trail is shared across many regions; will the event always come from the region the trail was created in? Or the region the event was triggered from?  I took the following steps to test:
1) Created a trail called "shared-trail-bronagh" in N. Virgina (us-east-1) and configured it to apply to all regions.
2) Logged into the N. California region and verified the trail had been replicated from 1) above.
3) I rebooted a VM that exists in N. California and did not see an event get fired from either region.
4) Remaining in the N. California region, I added a CloudWatch event rule for the EC2 service called "ec2_Rule" that would match ALL EC2 events, I set the target to the local AWSConfig_topic that exists for N. California.
5) I rebooted the VM from step 3) again (looks like I didn't need to reboot a second time but I did).
6) I received two events of [this](https://gist.github.com/bronaghs/b645a654955718c67dff6d1fdf3586d2) format, note the following properties:
```
detail-type:  AWS API Call via CloudTrail
eventType:    RebootInstances
event_source: :cloud_watch_api
```

So it looks like when a trail is "Applied to all regions" a copy is completely handed off to each individual region for processing separately from the region the trail was created in and when an event is triggered it will be sent to the AWSConfig_topic local to that region. This means:
- events will not be duplicated across multiple EMSes in ManageIQ
- events will not have a source equal to the region the trail was initially created in regardless of which region the event was triggered in.

@ladas @durandom  - Can you think of anything I missed? I will look at the role IAM accounts plays in this next.

**Comment by durandom** [comment]
@bronaghs sounds good.

One thing regarding AWS_Config, we create the queue and the topic automatically - but we dont destroy it, when the provider is removed. I know from QE that it can lead to some cost.
But thats probably something to defer, I just wanted to mention it.

**Comment by JPrause** [comment]
@bronaghs is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by djberg96** [comment]
Closing since this is old and the pivotal issue appears to be gone. We can reopen as needed.
