### ISSUE TITLE
Event filtering through configuration

### ISSUE THREAD

**Issue by bronaghs** [ManageIQ/manageiq-providers-amazon#140]
This issue identifies how event filtering is done today under the covers and explores a way to make it configurable to the end user.

### Option 1 - Blacklist table
There is a table called the "blacklisted_events" that stores event types that will be filtered out for a specific provider type. The only way to populate this table today is by:

1. Hardcoding the event types in the CloudManager.rb file of the providers, eg:
https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/app/models/manageiq/providers/amazon/cloud_manager.rb#L105:111

2. Adding rows through the rails console, like this:
`BlacklistedEvent.create(:event_name => "filter_me", :provider_model => "ManageIQ::Providers::Amazon::CloudManager")`

### Option 2 - Event storms
Duplicate events that are received en mass within a short timeframe are considered an event storm and are de-duplicated for the VMware provider.
I am not sure this functionality can be leveraged for this purpose; configuring the handling of event storms is not available to the end user and it addresses a different use case.

Given that the `BlacklistedEvents` class and the corresponding table already exist for the purposes of event filtering, I think it makes sense to leverage it. One place to configure this blacklist is the settings.yml file, this file already has an event_handling section but it is enormous and looks like it needs to be moved out to its own file. I think a new events_setting.yml file should be created for each provider as follows:
crawl - it would support a blacklist of event types to be filtered
walk  - move over the entire `event_handling` section

**Comment by bronaghs** [comment]
Pivotal story:
https://www.pivotaltracker.com/story/show/139861047

**Comment by bascar** [comment]
This sounds like a good path forward for a crawl phase.

**Comment by bronaghs** [comment]
@bascar - great, thanks

**Comment by bronaghs** [comment]
Actually, amazon got its own settings file in December past, no need to create one then.

**Comment by durandom** [comment]
>  One place to configure this blacklist is the settings.yml file, this file already has an event_handling section but it is enormous and looks like it needs to be moved out to its own file.

See the reasoning in https://github.com/ManageIQ/manageiq-providers-amazon/pull/138
Looks like "events_setting.yml" is not really the way to go, because it would require its own UI and bad (see jasons replies)

But once the events are put under their own key, I can see also moving the blacklisted events close to them.

I'm not sure though why the Blacklisted events are ActiveRecord objects in the DB and if they are needed to be in the DB - cause this would require seeding then.

**Comment by bronaghs** [comment]
@durandom 
So I realized Amazon has its own settings file so I decided to put the blacklisted events setting there, the same can be done for other providers in the future.
The heavy lifting has already been done around the blacklisted events functionality, the table gets seeded [here](https://github.com/ManageIQ/manageiq/blob/master/app/models/manageiq/providers/base_manager/event_catcher/runner.rb#L22).

**Comment by durandom** [comment]
@bronaghs maybe I'm missing something, but right now the blacklisted events are only in the db and in code (see your comment above) - **not** in settings.yml

I like adding this to the settings file

**Comment by bronaghs** [comment]
@durandom - thats what this issue is all about... Im adding a :blacklisted_events setting to the provider (amazon for now) settings file :-)

**Comment by bronaghs** [comment]
@durandom - ah! You are already tackling the gigantic list of events in the settings.yml file [#13942](#13942), exactly what I envisioned in the walk phase above. Nice.

**Comment by bronaghs** [comment]
fixed by #141
