### ISSUE TITLE
Map AWS Tags to MIQ Tags

### ISSUE THREAD

**Issue by bronaghs** [ManageIQ/manageiq-providers-amazon#167]
This GitHub issue outlines the steps involved in translating AWS Tags, referred to as labels here, to ManageIQ Tags. 

1) A user will map an AWS label name to a MIQ category through the "Map Tags" tab in the configuration page of the UI. For example:
    &nbsp;&nbsp;&nbsp;&nbsp;AWS Label:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**AWS_Tier = Gold**
    &nbsp;&nbsp;&nbsp;&nbsp;MIQ Mapping:&nbsp;&nbsp;&nbsp;&nbsp;**AWS_Tier = MIQ_Tier**
At this point:
a) A row in the Tags table will be created (check Classifications table too), note we call this a "category".
b) A ContainerLabelTagMapping, or a generic version of this class, will be instantiated with the AWS label name and the Tag ID of the category created in a) above, this can be inspected through the rails console.

2) An EMS refresh will be kicked off for AWS

3) During the refresh:
     a) The AWS Labels are parsed for a particular resource 
     b) A Tag object is created for the label value
     c) A Tagging object is instantiated and saved to the taggings table which stores:
&nbsp;&nbsp;&nbsp;&nbsp; - resource Id
&nbsp;&nbsp;&nbsp;&nbsp; - Tag id
*but only if a mapping was created for this label in step 1).*

Continuing with the example above, any resources with the AWS label "AWS_Tier" = "Gold" will have a "MIQ_Tier"  = "Gold" tag assigned to it and visible in the "My Company Tag" box of the resource Summary page. Any AWS labels without a mapping will be dropped.

**Comment by djberg96** [comment]
One thing I noticed is that when you create a label and category on the "Map Taggings" tab, it scopes the tag name to kubernetes:

"/managed/kubernetes::amazon_label"

I'm guessing we'll need to address that.

**Comment by blomquisg** [comment]
@djberg96 might be worth checking if the UI is enforcing that.

**Comment by djberg96** [comment]
Another possible issue is that when you create a tag/category via the Map Tags tab, it sets the `read_only` to true, which means that it won't show up within the UI.

**Comment by bronaghs** [comment]
We received this feedback from @bascar:

As an enhancement, it would be great if we could pick a specific tag category and auto create the tag value. I am thinking something like: 
- AWS Label:                            "myCompany_department" = "HR"
If we wild-carded(create if doesn't exist) the category of  "myCompany_department" , then it would match to "HR" or create "HR" if it does not exists. That way categories that exhibit a lot of adds dont have to be manually mapped.
- MIQ Mapping:                        "company_department" = "HR"
 ​

**Comment by cben** [comment]
"wildcard" is what the container "Map Tags" feature already does.
The mapping is for specific key ("myCompany_department") -> a category, finds or creates tag per value as needed. [*]

ContainerLabelTagMapping class also supports mapping a single value, but that was never documented nor exposed in UI, I'm all for dropping it to simplify the code
(unless you have a use for it. it would complicate the UI, especially logic for deleting mappings & categories. would need someone to decide exact requirements first.)

[*] BTW I forgot to warn you, that tag creation code does some DB locking, might kill your shiny graph refresh performance ;-)  https://github.com/ManageIQ/manageiq/blob/a684fcfa52/app/models/container_label_tag_mapping.rb#L74-L94
The motivation was that tags and classifications tables are shared for the region, wanted different providers' refresh workers that want to create same tag to achieve atomic upsert.  There are probably better ways.

**Comment by djberg96** [comment]
@cben Where are we on this?

**Comment by juliancheal** [comment]
> One thing I noticed is that when you create a label and category on the "Map Tags" tab, it scopes the tag name to kubernetes:

In my db I have `/managed/amazon:vm:santa`

**Comment by bronaghs** [comment]
@juliancheal -  I too get the correct value in the taggings table: /managed/amazon:vm:aws_tier
I think the comment Dan made was fixed, he made it on March 7th.

**Comment by juliancheal** [comment]
@bronaghs thanks! I realised after I posted that this wasn't all from now! 😂

**Comment by cben** [comment]
> @cben Where are we on this?

You tell me :-)
I believe this issue could have been closed — it has all worked at some stage.
However now tag mapping is broken in amazon — https://bugzilla.redhat.com/show_bug.cgi?id=1506404 , I'm not sure if that's just because of switch to graph refresh (expected) or also broken in classical refresh — details on the BZ.

I'm happy to help next week, but need a failing test or at least VCR / sample of refresh parser inputs to work on this.

**Comment by djberg96** [comment]
Looks like https://bugzilla.redhat.com/show_bug.cgi?id=1506404 was moved to POST. Can we close this?
