### ISSUE TITLE
Write specs for tag setting 

### ISSUE THREAD

**Issue by bronaghs** [ManageIQ/manageiq-providers-amazon#201]
PR https://github.com/ManageIQ/manageiq-providers-amazon/pull/183 still needs to be ported to the new graph refresh. Given that the [spec](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb ) is running against the old and the new (graph) refresh, it will fail when the graph refresh is merged. For this reason, the tagging spec test was commented out but it needs to be enabled after tagging support has been added to the graph refresh.

**Comment by djberg96** [comment]
@AlexanderZagaynov @tumido Did either one of you already do this? If not, can we use the ones from Azure?

**Comment by AlexanderZagaynov** [comment]
@djberg96 I haven't heard about this particular issue before. 
However, I did some tagging specs for Azure, maybe it can help you:
https://github.com/ManageIQ/manageiq-providers-azure/pull/231
https://github.com/ManageIQ/manageiq-providers-azure/pull/229

**Comment by JPrause** [comment]
@djberg96 is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.
