### ISSUE TITLE
Extend tag support for network and storage object types

### ISSUE THREAD

**Issue by bronaghs** [ManageIQ/manageiq-providers-amazon#206]
Gather AWS tags for the following storage and network types:
Security Groups,
Network Interfaces,
Load Balancers,
Volumes,
Snapshots,
VPCs,
Route Tables,
Gateways
and S3 buckets

**Comment by JPrause** [comment]
@bronaghs is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by djberg96** [comment]
Unless there's a customer BZ for it, don't think it's gonna happen. Closing for now, can be reopened as needed.
