### ISSUE TITLE
A better way for building instance types list

### ISSUE THREAD

**Issue by jameswnl** [ManageIQ/manageiq-providers-amazon#302]
Currently we are using [this rake task](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/lib/tasks_private/instance_types.rake) which also involve pre-rake manual steps to retrieve info from multiple website. 

This procedure has to be done before each MIQ release. In between releases, user now can use [this (yet to be released) mechanism](https://github.com/ManageIQ/manageiq-providers-amazon/pull/289) to capture new instance types which missed the release train.

A better solution will be a web service that is always available to allow MIQ to retrieve. (Similar to what Azure has)

What we can do for now is to

1. contribute to https://github.com/powdahound/ec2instances.info to enhance its [json output](https://github.com/powdahound/ec2instances.info/blob/master/www/instances.json) to contain what we need

1. Adapt and move the logic in [this rake task](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/lib/tasks_private/instance_types.rake) to the [ManageIQ::Providers::Amazon::CloudManager::RefreshParser.get_flavors](https://github.com/ManageIQ/manageiq-providers-amazon/blob/6619a2677b19ca5706790ac1a2cd256089cda08f/app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb#L43) and/or [ManageIQ::Providers::Amazon::InstanceTypes.instance_types](https://github.com/ManageIQ/manageiq-providers-amazon/blob/5d3a5f8950878e75d9cbef6255213b9c04e0aaa9/app/models/manageiq/providers/amazon/instance_types.rb#L1890)

1. (MIQ would need access to http://www.ec2instances.info/)

I have 2 PRs moving in that direction.

- For 1., https://github.com/powdahound/ec2instances.info/pull/270 (merged)
- For 2, https://github.com/ManageIQ/manageiq-providers-amazon/pull/301 (merged)

**Comment by jameswnl** [comment]
@durandom @bronaghs @blomquisg FYI...

**Comment by juliancheal** [comment]
I love the idea, but don't like the thought of going to a third party.

**Comment by jameswnl** [comment]
@juliancheal yeah, I agree it's not ideal to depend on a 3rd party. But we have been depending on the same 3rd party, ` ec2instances.info` (since day 1?).  

Plus, this 3rd party is open source and it is depending on AWS's published html.

**Comment by juliancheal** [comment]
@jameswnl oh, I thought we read it direct from AWS's published pages.

**Comment by juliancheal** [comment]
@jameswnl as `ec2instances.info` is open source, could we mirror it?

**Comment by juliancheal** [comment]
@jameswnl are we still pursuing this?

**Comment by jameswnl** [comment]
@juliancheal closing this because https://github.com/ManageIQ/manageiq-providers-amazon/issues/396 seems a simpler approach.

**Comment by juliancheal** [comment]
@jameswnl I had a feeling @AlexanderZagaynov would have a solution :)

**Comment by AlexanderZagaynov** [comment]
yeah, there is the first one https://github.com/ManageIQ/manageiq-providers-amazon/pull/436
and if everyone likes that approach, I'll do the PRs for two other related issues too in the same way
