### ISSUE TITLE
Failure during smartstate agent setup leaves a zombie instance and job

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-providers-amazon#334]
If you start a scan job, and it tries to docker login when credentials are missing or one of the ssh commands fail, you get the error as expected in the log, but the job and the instance seems to be running forever.  This is because it never is part of the heartbeat check.  Even so, we should ensure that any failure during setup is caught directly and handled as opposed to relying on heartbeat.

**Comment by djberg96** [comment]
@roliveri Any update on this?

**Comment by roliveri** [comment]
@djberg96 I think this was resolved by Hui's PR:
https://github.com/ManageIQ/manageiq-providers-amazon/pull/367

@hsong-rh Is that correct? Should we just close this issue?

**Comment by hsong-rh** [comment]
Rich, yes, this issue have been solved already in #367.

**Comment by djberg96** [comment]
@hsong-rh Thanks for the update, closing.
