### ISSUE TITLE
smartstate docker creds fail validation and thus show errors in the UI

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-providers-amazon#335]
During the automated credential validation, smartstate creds go into an error state, and thus the entire EMS is marked as invalid (refresh stays up, but it's mostly a UI problem.

<img width="778" alt="manageiq cloud providers 2017-10-27 15-55-53" src="https://user-images.githubusercontent.com/52120/32122726-5cc8b286-bb2f-11e7-838d-dfb3c15bbfd6.png">

**Comment by Fryguy** [comment]
I entered the creds directly in Rails console since the UI creation of the creds isn't ready yet, but it will likely have the same problems even when the UI is updated.

**Comment by jerryk55** [comment]
@Fryguy I have my UI code disabled at the moment to record some screenshots but I'll check when I re-enable it.  The validation for the second set of crews is supposed to be disabled so it actually shouldn't show as failed.  I'm pretty sure after I added my providers with two sets of credentials there was a a green checkmark on the provider.  I'll validate my hypothesis in a little bit...

**Comment by jerryk55** [comment]
<img width="1189" alt="screen shot 2017-10-27 at 5 48 35 pm" src="https://user-images.githubusercontent.com/6118503/32126517-1f5daa72-bb3f-11e7-9daa-3be5fe0fc4eb.png">

 
@Fryguy you can see the default credentials are valid.  The Smartstate credentials aren't validated and show up with at status of "none" - we may have to tweak that  but you can see the EMS has the green checkmark.

**Comment by jerryk55** [comment]
Actually when the provider is added the credentials appear as above - but after the first scheduled verification job is run the status changes to failed because of the issue fixed in this PR: https://github.com/ManageIQ/manageiq-providers-amazon/pull/341.  @Fryguy this will need to be merged as well.
