### ISSUE TITLE
Memory metrics on AWS are not captured

### ISSUE THREAD

**Issue by rbergami** [ManageIQ/manageiq-providers-amazon#374]
AWS provider doesn't capture data related to memory usage of instances. Data is not showed in the UI.

[1] manageiq-providers-amazon/app/models/manageiq/providers/amazon/cloud_manager/metrics_capture.rb

**Comment by djberg96** [comment]
Was added by https://github.com/ManageIQ/manageiq-providers-amazon/pull/393.
