### ISSUE TITLE
Upgrade AWS SDK library to version 3

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-providers-amazon#465]
We are currently using version 2 of the aws-sdk for Ruby. Version 3 has been out for a few years now, so we should probably upgrade.

**Comment by AlexanderZagaynov** [comment]
@djberg96 I had to make changes in 3 gems. Now I need to test that somehow on Travis.
Problem that those gems have cross-dependencies, and can't be tested in a usual way.
They all should be tested on update branches of each other. Maybe you have some idea, how to do that?
Maybe we can create `aws_sdk_v3` branches in all of those MiQ repos, and point dependencies to it,
then test everything against those?

@tumido you did similar change on Google, maybe you can help?

And next thing I'm thinking about - is that since v3 gem was made modular, maybe we can just pick up only needed sub-gems? Need to do more research.

**Comment by jerryk55** [comment]
@AlexanderZagaynov someone has to be sure that this change does not impact the SSA functionality  of amazon_ssa_support.

**Comment by AlexanderZagaynov** [comment]
@jerryk55 can current specs suite provide such confidence?

**Comment by jerryk55** [comment]
Not entirely sure.  Probably should rope @hsong-rh into the discussion.  He did most of the work on that gem...

**Comment by hsong-rh** [comment]
@AlexanderZagaynov Current specs only use mocked data to test SSA logics, may not find aws sdk APIs problems, if there is any. It's better to run a real SSA job with V3 gem.

**Comment by AlexanderZagaynov** [comment]
@hsong-rh frankly speaking, I have no idea how to do that :)
can you point me on?

**Comment by AlexanderZagaynov** [comment]
Here is the logs from local testing. They have several weird errors, I'm going to investigate them.
[miq-core_aws-sdk_v3.log](https://github.com/ManageIQ/manageiq-providers-amazon/files/2405703/miq-core_aws-sdk_v3.log)
[miq-amazon_aws-sdk_v3.log](https://github.com/ManageIQ/manageiq-providers-amazon/files/2405704/miq-amazon_aws-sdk_v3.log)
[miq-ssa_aws-sdk_v3.log](https://github.com/ManageIQ/manageiq-providers-amazon/files/2405706/miq-ssa_aws-sdk_v3.log)
[miq-pending_aws-sdk_v3.log](https://github.com/ManageIQ/manageiq-providers-amazon/files/2405707/miq-pending_aws-sdk_v3.log)

**Comment by AlexanderZagaynov** [comment]
@djberg96 @agrare @jerryk55 @Fryguy @NickLaMuro @hsong-rh @carbonin 

I've updated those 3 PRs to fix found issues and prevent possible.
Main problem was requirements. 
It's not enough to require only `aws-sdk` now, need to require `aws-sdk-<service_name>`.
Some slight problems was with specs, mostly related to requirements thing above.

Attaching here my local testing logs:
[miq-core_aws-sdk_v3.log](https://github.com/ManageIQ/manageiq-providers-amazon/files/2469169/miq-core_aws-sdk_v3.log)
[miq-amazon_aws-sdk_v3.log](https://github.com/ManageIQ/manageiq-providers-amazon/files/2469172/miq-amazon_aws-sdk_v3.log)
[miq-pending_aws-sdk_v3.log](https://github.com/ManageIQ/manageiq-providers-amazon/files/2469174/miq-pending_aws-sdk_v3.log)
[miq-ssa_aws-sdk_v3.log](https://github.com/ManageIQ/manageiq-providers-amazon/files/2469175/miq-ssa_aws-sdk_v3.log)

**Comment by Fryguy** [comment]
So I did a grep on aws-sdk across all repos and there are a lot of places that I'm not sure have been tested...can you verify the rest of these?  I see you've urn the specs, but if these are not covered by specs, then they are missed.

I am also going off of your statement that "It's not enough to require aws-sdk only now, need to require aws-sdk-<service_name> instead", so I found a bunch of places where the code apparently doesn't do that.

### manageiq-providers-amazon
The following lines have `require 'aws-sdk'` without the individual service require:
- app/models/manageiq/providers/amazon/manager_mixin.rb:90
- spec/models/manageiq/providers/amazon/cloud_manager/refresh_parser_spec.rb:12
- spec/models/manageiq/providers/amazon/network_manager/refresh_parser_spec.rb:2

### amazon_ssa_support
There are a number of `require 'aws-sdk'` littered throughout the code without the individual service require.  Additionally I see you've run the specs, but did you do a real job run-through?  Perhaps @hsong-rh can help you with that if not?

### manageiq-gems-pending
gemspec was changed and patch removed, but there are `require`s in:
- https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/object_storage/miq_s3_storage.rb#L83-L84 (note line 84 still references the patch that was removed, so this should be failing anyway)

### manageiq
ManageIQ core has references to aws-sdk in app/models/file_depot_s3.rb also missing changes for individual services.  Have those been verified?

**Comment by djberg96** [comment]
@AlexanderZagaynov Where we at?
