### ISSUE TITLE
Can't seem to use a Rails console

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-providers-amazon#5]
Not sure if it's possible, but it would be nice to Rails console from this repo.  Not sure how that would work, or if it's even possible.

**Comment by durandom** [comment]
This exact question is discussed here and he has a PR :)
https://github.com/rails/rails/pull/22588

I'm also not quite sure how a productive development workflow would look like if you have to make changes to both sides: provider gem and manageiq

One idea is to keep working inside manageiq, clone into e.g. `gems.external/manageiq-providers-amazon` and tell bundler to use this
`bundle config local.manageiq-providers-amazon ~/src/manageiq/gems.external/manageiq-providers-amazon`

**Comment by Fryguy** [comment]
The other option is to just change the :git reference in the Gemfile to a path and then the dev can use whatever directory works for them.

**Comment by durandom** [comment]
Also see the section on provider developement here:
http://manageiq.org/documentation/development/developer_setup/

This is the best solution so far, imho, because you dont have to fiddle with the Gemfile in manageiq

**Comment by durandom** [comment]
Closing this, because the canonical developement way for now is to clone into a subdir in your manageiq directory
