### ISSUE TITLE
The new `create_from_params` doesn't create an endpoint relation, just the authentication

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-providers-amazon#594]
I tried to add a provider with the old and the new way at the same time and the latter one doesn't set up the endpoint.

**New:**
```ruby
ems.endpoints
=> []
```

**Old:**
```ruby
ems.endpoints
=> [#<Endpoint:0x0000000014b991a0...]
```

@miq-bot assign @agrare 
@miq-bot add_label bug

**Comment by djberg96** [comment]
@skateman This can be closed now, right?
