### ISSUE TITLE
Reuse setup files from manageiq

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-providers-amazon#6]
I'm wondering if instead of having a separate tools/ci/before_install.sh we can reuse the /spec/manageiq/bin/setup.  Or perhaps, change ManageIQ's tools/ci/before_install.sh to separate out those shared operations allowing it to be called from this repo's before_install.sh

**Comment by durandom** [comment]
Thats mostly adressed by https://github.com/ManageIQ/manageiq/pull/13278
