### ISSUE TITLE
AWS_EC2_Instance_DELETE events are not always received

### ISSUE THREAD

**Issue by john-dupuy** [ManageIQ/manageiq-providers-amazon#620]
I have a simple test case that will, 

1) Provision an instance on EC2
2) Delete the instance
3) Look for the `AWS_EC2_Instance_DELETE` event on the timeline of the instance

Out of three runs of this test, only 1 received the `AWS_EC2_Instance_DELETE` and it was not associated with the instance name. When running this manually, I will check the DB for the events, from those 3 test runs, the events received look like: 
```
vmdb_production=# select id, event_type, vm_name, source, timestamp from event_streams where source = 'AMAZON';
 id  |           event_type            |        vm_name         | source |        timestamp        
-----+---------------------------------+------------------------+--------+-------------------------
 567 | AWS_EC2_NetworkInterface_CREATE |                        | AMAZON | 2020-04-27 12:26:03.122
 568 | AWS_EC2_VPC_UPDATE              |                        | AMAZON | 2020-04-27 12:26:03.098
 569 | AWS_EC2_Subnet_UPDATE           |                        | AMAZON | 2020-04-27 12:26:03.175
 570 | AWS_EC2_SecurityGroup_UPDATE    |                        | AMAZON | 2020-04-27 12:26:03.16
 571 | AWS_EC2_Volume_CREATE           |                        | AMAZON | 2020-04-27 12:26:03.143
 572 | AWS_EC2_Instance_CREATE         | test-event-vcqj-jdupuy | AMAZON | 2020-04-27 12:26:03.201
 573 | AWS_EC2_Instance_DELETE         |                        | AMAZON | 2020-04-27 12:28:19.663
 574 | AWS_EC2_SecurityGroup_UPDATE    |                        | AMAZON | 2020-04-27 12:28:19.696
 575 | AWS_EC2_Subnet_UPDATE           |                        | AMAZON | 2020-04-27 12:28:19.713
 576 | AWS_EC2_VPC_UPDATE              |                        | AMAZON | 2020-04-27 12:28:19.679
 583 | AWS_EC2_Volume_CREATE           |                        | AMAZON | 2020-04-27 13:16:44.214
 584 | AWS_EC2_NetworkInterface_CREATE |                        | AMAZON | 2020-04-27 13:16:44.187
 585 | AWS_EC2_Instance_CREATE         | test-event-wwf4-jdupuy | AMAZON | 2020-04-27 13:16:44.274
 586 | AWS_EC2_SecurityGroup_UPDATE    |                        | AMAZON | 2020-04-27 13:16:44.231
 587 | AWS_EC2_VPC_UPDATE              |                        | AMAZON | 2020-04-27 13:16:44.161
 588 | AWS_EC2_Subnet_UPDATE           |                        | AMAZON | 2020-04-27 13:16:44.248
 590 | AWS_EC2_NetworkInterface_CREATE |                        | AMAZON | 2020-04-27 13:26:50.395
 591 | AWS_EC2_Volume_CREATE           |                        | AMAZON | 2020-04-27 13:26:50.371
 592 | AWS_EC2_VPC_UPDATE              |                        | AMAZON | 2020-04-27 13:26:50.347
 593 | AWS_EC2_SecurityGroup_UPDATE    |                        | AMAZON | 2020-04-27 13:26:50.411
 594 | AWS_EC2_Subnet_UPDATE           |                        | AMAZON | 2020-04-27 13:26:50.426
 595 | AWS_EC2_Instance_CREATE         | test-event-wg6c-jdupuy | AMAZON | 2020-04-27 13:26:50.451
```
Testing was carried out in the downstream build of 5.11.5.2. Since the create events are received, I would also expect the delete events to be received as well.

**Comment by djberg96** [comment]
@john-dupuy Can you show me your settings for aws event handling? I just want to make sure there's nothing unusual there.

**Comment by john-dupuy** [comment]
@djberg96 I haven't touched the defaults for the `ems_amazon` config in the advanced settings yaml:
```yaml
  :ems_amazon:
    :event_handling:
      :event_groups:
        :addition:
          :critical:
          - AWS_EC2_Instance_CREATE
          - AWS_API_CALL_RunInstances
          - AWS_API_CALL_CreateTags
        :update:
          :critical:
          - AWS_EC2_Instance_UPDATE
        :deletion:
          :critical:
          - AWS_EC2_Instance_DELETE
          - AWS_API_CALL_TerminateInstances
        :power:
          :critical:
          - AWS_EC2_Instance_running
          - AWS_EC2_Instance_shutting-down
          - AWS_EC2_Instance_stopped
          - EC2_Instance_State_change_Notification_running
          - EC2_Instance_State_change_Notification_shutting_down
          - EC2_Instance_State_change_Notification_stopped
          - EC2_Instance_State_change_Notification_stopping
          - EC2_Instance_State_change_Notification_terminated
          - EC2_Instance_State_change_Notification_pending
          - AWS_API_CALL_StopInstances
          - AWS_API_CALL_StartInstances
```

**Comment by djberg96** [comment]
Not sure it's significant, but I think it was first added here: https://bugzilla.redhat.com/show_bug.cgi?id=1207865

**Comment by djberg96** [comment]
@john-dupuy Can you test against master? I want to see if https://github.com/ManageIQ/manageiq-providers-amazon/pull/633 made any difference. I'll do some testing on my end, too.

**Comment by john-dupuy** [comment]
@djberg96 I don't have a way to test against master but I can pull the latest downstream appliance and apply the change that #633 brought in and test with that. Would that be enough?

**Comment by djberg96** [comment]
@john-dupuy That should work.

**Comment by djberg96** [comment]
As per our discussions offline, we are not able to replicate this. I tried termination via the console, the app, and a standalone script. In all cases I received two events per termination - `AWS_API_CALL_TerminateInstances` (start of termination) followed a couple minutes later by `AWS_EC2_Instance_DELETE` (termination complete).

At this point we're not sure if it's a 5.11 vs master issue or if it's something to do with the way the test case is setup. Still investigating...

**Comment by john-dupuy** [comment]
After some more investigation it looks like this was a case of our EC2 instance being misconfigured. I (loosely) followed the steps outlined https://www.manageiq.org/docs/guides/providers/amazon_aws_config and got this working again. 

EC2 has changed quite a bit since those docs were written so I had to create a `Rule` under the CloudWatch Events to send them to the SNS Topic. 

![Screenshot from 2020-07-31 16-39-21](https://user-images.githubusercontent.com/44065123/89075683-c38d1600-d34c-11ea-93e1-e272b9baf97e.png)
