### ISSUE TITLE
AWS Network(VPC) in CFME has no relationship with Network Router(Route Table)

### ISSUE THREAD

**Issue by dmetzger57** [ManageIQ/manageiq-providers-amazon#635]
Original BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1746862

Description of problem:
AWS Network(VPC) in CFME has no relationship with Network Router(Route Table)

How reproducible:
Always

Steps to Reproduce:
1. Add VPC in AWS
2. It automatically creates subresources like Main Route Table which is associated to VPC
Actual results:
In CFME Network-> Networks -> AWS Network(VPC) has zero associations in Relationships to Network Routers even when VPC must have at least main router.

**Comment by djberg96** [comment]
I think this addressed that: https://github.com/ManageIQ/manageiq-providers-amazon/pull/621
