### ISSUE TITLE
AWS VPC Security Groups and Network Ports(Network Interfaces) don't use in CFME Name field for naming

### ISSUE THREAD

**Issue by dmetzger57** [ManageIQ/manageiq-providers-amazon#636]
Original BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1746864

Description of problem:

How reproducible:
Always

Steps to Reproduce:
1. Create in AWS Security Group and set tag Name to something
2. Create in AWS Network Interface and set tag Name to something
Actual results:
For Security Groups naming is taken from Group Name.
For Network Interface naming is taken from Interface ID.

Expected results:
It should take naming from Name tag if set same as for other resources from AWS.

**Comment by djberg96** [comment]
Curiously, the AWS API returns tags for network interfaces as a `tag_set` instead of just `tags`, so it wasn't as easy as I'd hoped.

**Comment by djberg96** [comment]
Fixed with https://github.com/ManageIQ/manageiq-providers-amazon/pull/638
