### ISSUE TITLE
EC2 Volume size change is not detected by targeted refresh

### ISSUE THREAD

**Issue by dmetzger57** [ManageIQ/manageiq-providers-amazon#637]
Original BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1754874

Description of problem:
When changing volume size in AWS there is no targeted refresh for it in CFME.

How reproducible:
Always

Steps to Reproduce:
1. Have ec2 provider with a volume
2. Change volume size in AWS
3. wait for targeted refresh of volume

Actual results:
Volume is not refreshed and has same size until manual refresh of volume provider is triggered.

**Comment by djberg96** [comment]
Can confirm. I modified a volume, and I can definitely see the event get picked up in the log, but the database is not updated.

**Comment by djberg96** [comment]
Solved with https://github.com/ManageIQ/manageiq-providers-amazon/pull/639 and https://github.com/ManageIQ/manageiq-content/pull/663
