### ISSUE TITLE
[RFE] Support Amazon EKS

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/manageiq-providers-amazon#682]
Add an Amazon::ContainerManager which subclasses the main Kubernetes::ContainerManager to support Amazon Web Service's Elastic Kubernetes Service (https://aws.amazon.com/eks/)

- [x] [Full Refresh](https://github.com/ManageIQ/manageiq-providers-amazon/pull/679)
- [x] [Streaming Refresh](https://github.com/ManageIQ/manageiq-providers-amazon/pull/680)
- [x] [Fix Scheduled Authentication Check](https://github.com/ManageIQ/manageiq-providers-amazon/pull/683)
- [x] [Add Icon for EKS](https://github.com/ManageIQ/manageiq-decorators/pull/45)

**Comment by agrare** [comment]
Alright I think we can call this one complete
