### ISSUE TITLE
Add a new region to regions.yml

### ISSUE THREAD

**Issue by tiiibs** [ManageIQ/manageiq-providers-amazon#732]
Hi,

We have a cloud provider that offers "aws compatible" API that we would like to test with ManageIQ. I didn't find the way to add a new region.  Adding a custom Endpoint URL on UI doesn't help.

**Comment by agrare** [comment]
Hey @tiiibs check out the amazon provider docs, https://www.manageiq.org/docs/reference/latest/managing_providers/cloud_providers/amazon_ec2_providers.html#adding-amazon-cloud-regions

**Comment by tiiibs** [comment]
Thank you!!!
